// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetAppSettings returns the persisted app settings or defaults if the file does not exist.
 */
export function GetAppSettings(): $CancellablePromise<$models.AppSettings> {
    return $Call.ByID(55540836).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * SaveAppSettings persists the provided settings to disk.
 */
export function SaveAppSettings(settings: $models.AppSettings): $CancellablePromise<$models.AppSettings> {
    return $Call.ByID(39874379, settings).then(($result: any) => {
        return $$createType0($result);
    });
}

// Private type creation functions
const $$createType0 = $models.AppSettings.createFrom;
