// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AuthService handles authentication with the server
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../time/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetAccessToken returns the current access token
 */
export function GetAccessToken(): $CancellablePromise<string> {
    return $Call.ByID(954703531);
}

/**
 * GetCurrentUser returns the current authenticated user
 */
export function GetCurrentUser(): $CancellablePromise<$models.User | null> {
    return $Call.ByID(3185623342).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetTokenExpirationTime returns when the current access token will expire
 */
export function GetTokenExpirationTime(): $CancellablePromise<time$0.Time> {
    return $Call.ByID(807832613);
}

/**
 * GetUserProfile fetches the current user profile from the server
 * This allows refreshing the user info (including role) without re-authentication
 * Note: This method requires an authenticated client to be set via SetAuthenticatedClient
 */
export function GetUserProfile(): $CancellablePromise<$models.User | null> {
    return $Call.ByID(360682264).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * IsAuthenticated checks if the user is authenticated
 * Attempts to refresh token if expired before returning false
 */
export function IsAuthenticated(): $CancellablePromise<boolean> {
    return $Call.ByID(3968808667);
}

/**
 * Login authenticates a user with email and password
 */
export function Login(email: string, password: string): $CancellablePromise<$models.AuthResponse | null> {
    return $Call.ByID(2079202709, email, password).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * Logout clears the authentication tokens
 */
export function Logout(): $CancellablePromise<void> {
    return $Call.ByID(3822607102);
}

/**
 * RefreshIfNeeded checks if token needs refresh and refreshes if necessary
 * Returns true if refresh was attempted, regardless of success
 */
export function RefreshIfNeeded(): $CancellablePromise<boolean> {
    return $Call.ByID(338574125);
}

/**
 * Register creates a new user account
 */
export function Register(email: string, password: string, name: string): $CancellablePromise<$models.AuthResponse | null> {
    return $Call.ByID(616699185, email, password, name).then(($result: any) => {
        return $$createType3($result);
    });
}

// Private type creation functions
const $$createType0 = $models.User.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $models.AuthResponse.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
