// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * BackgroundSyncService manages background synchronization tasks
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../time/models.js";

/**
 * IsRunning returns whether the background sync service is running
 */
export function IsRunning(): $CancellablePromise<boolean> {
    return $Call.ByID(2779834064);
}

/**
 * SetConfigSyncInterval sets the interval for config sync
 */
export function SetConfigSyncInterval(interval: time$0.Duration): $CancellablePromise<void> {
    return $Call.ByID(3653985111, interval);
}

/**
 * SetTokenRefreshInterval sets the interval for token refresh
 */
export function SetTokenRefreshInterval(interval: time$0.Duration): $CancellablePromise<void> {
    return $Call.ByID(1504347790, interval);
}

/**
 * SetUsageSyncInterval sets the interval for usage sync
 */
export function SetUsageSyncInterval(interval: time$0.Duration): $CancellablePromise<void> {
    return $Call.ByID(893083232, interval);
}

/**
 * Start begins the background sync processes
 */
export function Start(): $CancellablePromise<void> {
    return $Call.ByID(2433284443);
}

/**
 * Stop gracefully stops all background sync processes
 */
export function Stop(): $CancellablePromise<void> {
    return $Call.ByID(3875303817);
}

/**
 * SyncNow triggers an immediate sync of both config and usage
 */
export function SyncNow(): $CancellablePromise<[boolean, number]> {
    return $Call.ByID(145732950);
}
