// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function DisableProxy(): $CancellablePromise<void> {
    return $Call.ByID(3815925570);
}

export function EnableProxy(): $CancellablePromise<void> {
    return $Call.ByID(922948163);
}

export function ProxyStatus(): $CancellablePromise<$models.ClaudeProxyStatus> {
    return $Call.ByID(419975348).then(($result: any) => {
        return $$createType0($result);
    });
}

// Private type creation functions
const $$createType0 = $models.ClaudeProxyStatus.createFrom;
