// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ConfigSyncService handles synchronization of provider configurations from server
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../time/models.js";

/**
 * GetLastSyncTime returns the last successful sync time
 */
export function GetLastSyncTime(): $CancellablePromise<time$0.Time> {
    return $Call.ByID(2155464647);
}

/**
 * PushProvidersToServer pushes local provider changes to the server
 * This includes creating new providers, updating existing ones, and deleting removed ones
 */
export function PushProvidersToServer(): $CancellablePromise<void> {
    return $Call.ByID(2926888669);
}

/**
 * SyncProviderType syncs only a specific provider type (claude, codex, opencode)
 */
export function SyncProviderType(kind: string): $CancellablePromise<void> {
    return $Call.ByID(2280845705, kind);
}

/**
 * SyncProviders fetches and syncs all providers from the server
 * Uses the Provider API endpoint and the shared ConfigBuilder to build configs locally
 */
export function SyncProviders(): $CancellablePromise<void> {
    return $Call.ByID(3308450390);
}
