// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ConfigService manages config.json file containing app, server, and sync settings
 * Thread-safe with mutex for concurrent access
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ClearSyncState resets the sync state to zero time (never synced)
 * This is used during logout to ensure fresh sync state on next login
 */
export function ClearSyncState(): $CancellablePromise<void> {
    return $Call.ByID(3589730615);
}

/**
 * GetApp returns the app settings from config
 */
export function GetApp(): $CancellablePromise<$models.AppSettings> {
    return $Call.ByID(374038863).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * GetServer returns the server config from config
 */
export function GetServer(): $CancellablePromise<$models.ServerConfig> {
    return $Call.ByID(2721367375).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetSync returns the sync state from config
 */
export function GetSync(): $CancellablePromise<$models.SyncState> {
    return $Call.ByID(2247912175).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * Load loads the entire config from disk
 */
export function Load(): $CancellablePromise<$models.AppConfig> {
    return $Call.ByID(1429925260).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * Save saves the entire config to disk atomically
 */
export function Save(config: $models.AppConfig): $CancellablePromise<void> {
    return $Call.ByID(2685850893, config);
}

/**
 * SetApp saves the app settings to config
 */
export function SetApp(settings: $models.AppSettings): $CancellablePromise<void> {
    return $Call.ByID(1260506891, settings);
}

/**
 * SetServer saves the server config to config
 */
export function SetServer(server: $models.ServerConfig): $CancellablePromise<void> {
    return $Call.ByID(3551937355, server);
}

/**
 * SetSync saves the sync state to config
 */
export function SetSync(sync: $models.SyncState): $CancellablePromise<void> {
    return $Call.ByID(32594651, sync);
}

// Private type creation functions
const $$createType0 = $models.AppSettings.createFrom;
const $$createType1 = $models.ServerConfig.createFrom;
const $$createType2 = $models.SyncState.createFrom;
const $$createType3 = $models.AppConfig.createFrom;
