// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function GetStatus(): $CancellablePromise<$models.ConfigImportStatus> {
    return $Call.ByID(2109164227).then(($result: any) => {
        return $$createType0($result);
    });
}

export function GetStatusForFile(path: string): $CancellablePromise<$models.ConfigImportStatus> {
    return $Call.ByID(1419757440, path).then(($result: any) => {
        return $$createType0($result);
    });
}

export function ImportAll(): $CancellablePromise<$models.ConfigImportResult> {
    return $Call.ByID(124174517).then(($result: any) => {
        return $$createType1($result);
    });
}

export function ImportFromFile(path: string): $CancellablePromise<$models.ConfigImportResult> {
    return $Call.ByID(3740366900, path).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * ImportFromJSON imports configuration from in-memory JSON data
 */
export function ImportFromJSON(data: string): $CancellablePromise<$models.ConfigImportResult> {
    return $Call.ByID(752187916, data).then(($result: any) => {
        return $$createType1($result);
    });
}

export function Start(): $CancellablePromise<void> {
    return $Call.ByID(3119656637);
}

export function Stop(): $CancellablePromise<void> {
    return $Call.ByID(2083779375);
}

// Private type creation functions
const $$createType0 = $models.ConfigImportStatus.createFrom;
const $$createType1 = $models.ConfigImportResult.createFrom;
