// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../internal/models/models.js";

export function HeatmapStats(days: number): $CancellablePromise<models$0.HeatmapStat[]> {
    return $Call.ByID(1056815029, days).then(($result: any) => {
        return $$createType1($result);
    });
}

export function ListProviders(platform: string): $CancellablePromise<string[]> {
    return $Call.ByID(790916236, platform).then(($result: any) => {
        return $$createType2($result);
    });
}

export function ListRequestLogs(platform: string, provider: string, limit: number): $CancellablePromise<models$0.RequestLog[]> {
    return $Call.ByID(1199056012, platform, provider, limit).then(($result: any) => {
        return $$createType4($result);
    });
}

export function ProviderDailyStats(platform: string): $CancellablePromise<models$0.ProviderDailyStat[]> {
    return $Call.ByID(974013659, platform).then(($result: any) => {
        return $$createType6($result);
    });
}

export function StatsSince(platform: string): $CancellablePromise<models$0.LogStats> {
    return $Call.ByID(2831143405, platform).then(($result: any) => {
        return $$createType7($result);
    });
}

// Private type creation functions
const $$createType0 = models$0.HeatmapStat.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $Create.Array($Create.Any);
const $$createType3 = models$0.RequestLog.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = models$0.ProviderDailyStat.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = models$0.LogStats.createFrom;
