// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function ListServers(): $CancellablePromise<$models.MCPServer[]> {
    return $Call.ByID(1793630588).then(($result: any) => {
        return $$createType1($result);
    });
}

export function SaveServers(servers: $models.MCPServer[]): $CancellablePromise<void> {
    return $Call.ByID(2073851319, servers);
}

// Private type creation functions
const $$createType0 = $models.MCPServer.createFrom;
const $$createType1 = $Create.Array($$createType0);
