// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../time/models.js";

/**
 * AppConfig combines app settings, server config, and sync state into a single config
 * This is stored in config.json for non-sensitive application settings
 */
export class AppConfig {
    "app": AppSettings;
    "server": ServerConfig;
    "sync": SyncState;

    /** Creates a new AppConfig instance. */
    constructor($$source: Partial<AppConfig> = {}) {
        if (!("app" in $$source)) {
            this["app"] = (new AppSettings());
        }
        if (!("server" in $$source)) {
            this["server"] = (new ServerConfig());
        }
        if (!("sync" in $$source)) {
            this["sync"] = (new SyncState());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AppConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): AppConfig {
        const $$createField0_0 = $$createType0;
        const $$createField1_0 = $$createType1;
        const $$createField2_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("app" in $$parsedSource) {
            $$parsedSource["app"] = $$createField0_0($$parsedSource["app"]);
        }
        if ("server" in $$parsedSource) {
            $$parsedSource["server"] = $$createField1_0($$parsedSource["server"]);
        }
        if ("sync" in $$parsedSource) {
            $$parsedSource["sync"] = $$createField2_0($$parsedSource["sync"]);
        }
        return new AppConfig($$parsedSource as Partial<AppConfig>);
    }
}

export class AppSettings {
    "show_heatmap": boolean;
    "show_home_title": boolean;
    "show_24h_stats": boolean;
    "auto_start": boolean;

    /** Creates a new AppSettings instance. */
    constructor($$source: Partial<AppSettings> = {}) {
        if (!("show_heatmap" in $$source)) {
            this["show_heatmap"] = false;
        }
        if (!("show_home_title" in $$source)) {
            this["show_home_title"] = false;
        }
        if (!("show_24h_stats" in $$source)) {
            this["show_24h_stats"] = false;
        }
        if (!("auto_start" in $$source)) {
            this["auto_start"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AppSettings instance from a string or object.
     */
    static createFrom($$source: any = {}): AppSettings {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AppSettings($$parsedSource as Partial<AppSettings>);
    }
}

/**
 * AuthResponse represents a successful auth response from server
 */
export class AuthResponse {
    "access_token": string;
    "refresh_token": string;
    "user": User;
    "expires_at": time$0.Time;

    /** Creates a new AuthResponse instance. */
    constructor($$source: Partial<AuthResponse> = {}) {
        if (!("access_token" in $$source)) {
            this["access_token"] = "";
        }
        if (!("refresh_token" in $$source)) {
            this["refresh_token"] = "";
        }
        if (!("user" in $$source)) {
            this["user"] = (new User());
        }
        if (!("expires_at" in $$source)) {
            this["expires_at"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AuthResponse instance from a string or object.
     */
    static createFrom($$source: any = {}): AuthResponse {
        const $$createField2_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("user" in $$parsedSource) {
            $$parsedSource["user"] = $$createField2_0($$parsedSource["user"]);
        }
        return new AuthResponse($$parsedSource as Partial<AuthResponse>);
    }
}

export class ClaudeProxyStatus {
    "enabled": boolean;
    "base_url": string;

    /** Creates a new ClaudeProxyStatus instance. */
    constructor($$source: Partial<ClaudeProxyStatus> = {}) {
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }
        if (!("base_url" in $$source)) {
            this["base_url"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ClaudeProxyStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): ClaudeProxyStatus {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ClaudeProxyStatus($$parsedSource as Partial<ClaudeProxyStatus>);
    }
}

export class ConfigImportResult {
    "status": ConfigImportStatus;
    "imported_providers": number;
    "imported_mcp": number;

    /** Creates a new ConfigImportResult instance. */
    constructor($$source: Partial<ConfigImportResult> = {}) {
        if (!("status" in $$source)) {
            this["status"] = (new ConfigImportStatus());
        }
        if (!("imported_providers" in $$source)) {
            this["imported_providers"] = 0;
        }
        if (!("imported_mcp" in $$source)) {
            this["imported_mcp"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConfigImportResult instance from a string or object.
     */
    static createFrom($$source: any = {}): ConfigImportResult {
        const $$createField0_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("status" in $$parsedSource) {
            $$parsedSource["status"] = $$createField0_0($$parsedSource["status"]);
        }
        return new ConfigImportResult($$parsedSource as Partial<ConfigImportResult>);
    }
}

export class ConfigImportStatus {
    "config_exists": boolean;
    "config_path": string;
    "pending_providers": boolean;
    "pending_mcp": boolean;
    "pending_provider_count": number;
    "pending_mcp_count": number;

    /** Creates a new ConfigImportStatus instance. */
    constructor($$source: Partial<ConfigImportStatus> = {}) {
        if (!("config_exists" in $$source)) {
            this["config_exists"] = false;
        }
        if (!("config_path" in $$source)) {
            this["config_path"] = "";
        }
        if (!("pending_providers" in $$source)) {
            this["pending_providers"] = false;
        }
        if (!("pending_mcp" in $$source)) {
            this["pending_mcp"] = false;
        }
        if (!("pending_provider_count" in $$source)) {
            this["pending_provider_count"] = 0;
        }
        if (!("pending_mcp_count" in $$source)) {
            this["pending_mcp_count"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConfigImportStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): ConfigImportStatus {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ConfigImportStatus($$parsedSource as Partial<ConfigImportStatus>);
    }
}

/**
 * DailyReport represents the complete daily activity report
 */
export class DailyReport {
    /**
     * YYYY-MM-DD
     */
    "date": string;

    /**
     * Local timezone name
     */
    "timezone": string;

    /**
     * ISO timestamp
     */
    "generated_at": string;

    /**
     * Array of tool summaries
     */
    "tools": ToolReport[];

    /** Creates a new DailyReport instance. */
    constructor($$source: Partial<DailyReport> = {}) {
        if (!("date" in $$source)) {
            this["date"] = "";
        }
        if (!("timezone" in $$source)) {
            this["timezone"] = "";
        }
        if (!("generated_at" in $$source)) {
            this["generated_at"] = "";
        }
        if (!("tools" in $$source)) {
            this["tools"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DailyReport instance from a string or object.
     */
    static createFrom($$source: any = {}): DailyReport {
        const $$createField3_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tools" in $$parsedSource) {
            $$parsedSource["tools"] = $$createField3_0($$parsedSource["tools"]);
        }
        return new DailyReport($$parsedSource as Partial<DailyReport>);
    }
}

/**
 * DayDetails contains all statistics for a single natural day
 */
export class DayDetails {
    "session_stats": SessionStats;
    "event_type_counts": { [_: string]: number };
    "tool_usage_stats": ToolUsageItem[];
    "prompt_stats": PromptStats;

    /** Creates a new DayDetails instance. */
    constructor($$source: Partial<DayDetails> = {}) {
        if (!("session_stats" in $$source)) {
            this["session_stats"] = (new SessionStats());
        }
        if (!("event_type_counts" in $$source)) {
            this["event_type_counts"] = {};
        }
        if (!("tool_usage_stats" in $$source)) {
            this["tool_usage_stats"] = [];
        }
        if (!("prompt_stats" in $$source)) {
            this["prompt_stats"] = (new PromptStats());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DayDetails instance from a string or object.
     */
    static createFrom($$source: any = {}): DayDetails {
        const $$createField0_0 = $$createType7;
        const $$createField1_0 = $$createType8;
        const $$createField2_0 = $$createType10;
        const $$createField3_0 = $$createType11;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("session_stats" in $$parsedSource) {
            $$parsedSource["session_stats"] = $$createField0_0($$parsedSource["session_stats"]);
        }
        if ("event_type_counts" in $$parsedSource) {
            $$parsedSource["event_type_counts"] = $$createField1_0($$parsedSource["event_type_counts"]);
        }
        if ("tool_usage_stats" in $$parsedSource) {
            $$parsedSource["tool_usage_stats"] = $$createField2_0($$parsedSource["tool_usage_stats"]);
        }
        if ("prompt_stats" in $$parsedSource) {
            $$parsedSource["prompt_stats"] = $$createField3_0($$parsedSource["prompt_stats"]);
        }
        return new DayDetails($$parsedSource as Partial<DayDetails>);
    }
}

export class Hotkey {
    /**
     * 热键ID
     */
    "id": number;

    /**
     * 键码
     */
    "keycode": number;

    /**
     * 修饰键
     */
    "modifiers": number;

    /** Creates a new Hotkey instance. */
    constructor($$source: Partial<Hotkey> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("keycode" in $$source)) {
            this["keycode"] = 0;
        }
        if (!("modifiers" in $$source)) {
            this["modifiers"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Hotkey instance from a string or object.
     */
    static createFrom($$source: any = {}): Hotkey {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Hotkey($$parsedSource as Partial<Hotkey>);
    }
}

export class MCPServer {
    "name": string;
    "type": string;
    "command"?: string;
    "args"?: string[];
    "env"?: { [_: string]: string };
    "url"?: string;
    "website"?: string;
    "tips"?: string;
    "headers"?: { [_: string]: string };
    "enable_platform": string[];
    "enabled_in_claude": boolean;
    "enabled_in_codex": boolean;
    "enabled_in_opencode": boolean;
    "missing_placeholders": string[];

    /** Creates a new MCPServer instance. */
    constructor($$source: Partial<MCPServer> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("enable_platform" in $$source)) {
            this["enable_platform"] = [];
        }
        if (!("enabled_in_claude" in $$source)) {
            this["enabled_in_claude"] = false;
        }
        if (!("enabled_in_codex" in $$source)) {
            this["enabled_in_codex"] = false;
        }
        if (!("enabled_in_opencode" in $$source)) {
            this["enabled_in_opencode"] = false;
        }
        if (!("missing_placeholders" in $$source)) {
            this["missing_placeholders"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MCPServer instance from a string or object.
     */
    static createFrom($$source: any = {}): MCPServer {
        const $$createField3_0 = $$createType12;
        const $$createField4_0 = $$createType13;
        const $$createField8_0 = $$createType13;
        const $$createField9_0 = $$createType12;
        const $$createField13_0 = $$createType12;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("args" in $$parsedSource) {
            $$parsedSource["args"] = $$createField3_0($$parsedSource["args"]);
        }
        if ("env" in $$parsedSource) {
            $$parsedSource["env"] = $$createField4_0($$parsedSource["env"]);
        }
        if ("headers" in $$parsedSource) {
            $$parsedSource["headers"] = $$createField8_0($$parsedSource["headers"]);
        }
        if ("enable_platform" in $$parsedSource) {
            $$parsedSource["enable_platform"] = $$createField9_0($$parsedSource["enable_platform"]);
        }
        if ("missing_placeholders" in $$parsedSource) {
            $$parsedSource["missing_placeholders"] = $$createField13_0($$parsedSource["missing_placeholders"]);
        }
        return new MCPServer($$parsedSource as Partial<MCPServer>);
    }
}

/**
 * PromptStats contains prompt-related statistics
 */
export class PromptStats {
    "total_prompts": number;
    "average_prompt_length": number;
    "longest_prompt": number;
    "shortest_prompt": number;

    /** Creates a new PromptStats instance. */
    constructor($$source: Partial<PromptStats> = {}) {
        if (!("total_prompts" in $$source)) {
            this["total_prompts"] = 0;
        }
        if (!("average_prompt_length" in $$source)) {
            this["average_prompt_length"] = 0;
        }
        if (!("longest_prompt" in $$source)) {
            this["longest_prompt"] = 0;
        }
        if (!("shortest_prompt" in $$source)) {
            this["shortest_prompt"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PromptStats instance from a string or object.
     */
    static createFrom($$source: any = {}): PromptStats {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PromptStats($$parsedSource as Partial<PromptStats>);
    }
}

export class Provider {
    "id": number;
    "name": string;
    "apiUrl": string;
    "apiKey": string;
    "tint": string;
    "accent": string;
    "enabled": boolean;

    /**
     * Model whitelist - Models natively supported by Provider (exact or wildcard patterns)
     */
    "supportedModels"?: string[];

    /**
     * Model mapping - External model name -> Provider internal model name
     * Supports exact match and wildcard (e.g., "claude-*" -> "anthropic/claude-*")
     */
    "modelMapping"?: { [_: string]: string };

    /**
     * Priority grouping - Smaller number = higher priority (1-10, default 1)
     * Use omitempty to ensure zero values are not serialized, backward compatible
     */
    "level"?: number;

    /**
     * Team ID from server (used when pushing to server)
     * Use omitempty to ensure zero values are not serialized, backward compatible
     */
    "teamId"?: number;

    /** Creates a new Provider instance. */
    constructor($$source: Partial<Provider> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("apiUrl" in $$source)) {
            this["apiUrl"] = "";
        }
        if (!("apiKey" in $$source)) {
            this["apiKey"] = "";
        }
        if (!("tint" in $$source)) {
            this["tint"] = "";
        }
        if (!("accent" in $$source)) {
            this["accent"] = "";
        }
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Provider instance from a string or object.
     */
    static createFrom($$source: any = {}): Provider {
        const $$createField7_0 = $$createType12;
        const $$createField8_0 = $$createType13;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("supportedModels" in $$parsedSource) {
            $$parsedSource["supportedModels"] = $$createField7_0($$parsedSource["supportedModels"]);
        }
        if ("modelMapping" in $$parsedSource) {
            $$parsedSource["modelMapping"] = $$createField8_0($$parsedSource["modelMapping"]);
        }
        return new Provider($$parsedSource as Partial<Provider>);
    }
}

/**
 * ServerConfig stores the server connection configuration
 */
export class ServerConfig {
    "server_url": string;

    /** Creates a new ServerConfig instance. */
    constructor($$source: Partial<ServerConfig> = {}) {
        if (!("server_url" in $$source)) {
            this["server_url"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ServerConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): ServerConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ServerConfig($$parsedSource as Partial<ServerConfig>);
    }
}

/**
 * SessionInfo represents a single session's duration information
 */
export class SessionInfo {
    "session_id": string;

    /**
     * ISO timestamp
     */
    "begin_time": string;

    /**
     * Duration in milliseconds
     */
    "duration_ms": number;

    /**
     * Count of each event type in this session
     */
    "event_type_counts": { [_: string]: number };

    /**
     * Git repository name (e.g., "owner/repo")
     */
    "repository_name": string;

    /**
     * Git branch name
     */
    "branch": string;

    /**
     * Git commit hash
     */
    "commit_hash": string;

    /** Creates a new SessionInfo instance. */
    constructor($$source: Partial<SessionInfo> = {}) {
        if (!("session_id" in $$source)) {
            this["session_id"] = "";
        }
        if (!("begin_time" in $$source)) {
            this["begin_time"] = "";
        }
        if (!("duration_ms" in $$source)) {
            this["duration_ms"] = 0;
        }
        if (!("event_type_counts" in $$source)) {
            this["event_type_counts"] = {};
        }
        if (!("repository_name" in $$source)) {
            this["repository_name"] = "";
        }
        if (!("branch" in $$source)) {
            this["branch"] = "";
        }
        if (!("commit_hash" in $$source)) {
            this["commit_hash"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SessionInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): SessionInfo {
        const $$createField3_0 = $$createType8;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("event_type_counts" in $$parsedSource) {
            $$parsedSource["event_type_counts"] = $$createField3_0($$parsedSource["event_type_counts"]);
        }
        return new SessionInfo($$parsedSource as Partial<SessionInfo>);
    }
}

/**
 * SessionStats contains session-related statistics
 */
export class SessionStats {
    "session_count": number;
    "event_count": number;
    "unique_sessions": SessionInfo[];

    /** Creates a new SessionStats instance. */
    constructor($$source: Partial<SessionStats> = {}) {
        if (!("session_count" in $$source)) {
            this["session_count"] = 0;
        }
        if (!("event_count" in $$source)) {
            this["event_count"] = 0;
        }
        if (!("unique_sessions" in $$source)) {
            this["unique_sessions"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SessionStats instance from a string or object.
     */
    static createFrom($$source: any = {}): SessionStats {
        const $$createField2_0 = $$createType15;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("unique_sessions" in $$parsedSource) {
            $$parsedSource["unique_sessions"] = $$createField2_0($$parsedSource["unique_sessions"]);
        }
        return new SessionStats($$parsedSource as Partial<SessionStats>);
    }
}

export class Skill {
    "key": string;
    "name": string;
    "description": string;
    "directory": string;
    "readme_url": string;
    "installed": boolean;
    "repo_owner"?: string;
    "repo_name"?: string;
    "repo_branch"?: string;

    /** Creates a new Skill instance. */
    constructor($$source: Partial<Skill> = {}) {
        if (!("key" in $$source)) {
            this["key"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("directory" in $$source)) {
            this["directory"] = "";
        }
        if (!("readme_url" in $$source)) {
            this["readme_url"] = "";
        }
        if (!("installed" in $$source)) {
            this["installed"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Skill instance from a string or object.
     */
    static createFrom($$source: any = {}): Skill {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Skill($$parsedSource as Partial<Skill>);
    }
}

/**
 * SyncState tracks the last sync time
 */
export class SyncState {
    "last_sync_time": time$0.Time;

    /** Creates a new SyncState instance. */
    constructor($$source: Partial<SyncState> = {}) {
        if (!("last_sync_time" in $$source)) {
            this["last_sync_time"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SyncState instance from a string or object.
     */
    static createFrom($$source: any = {}): SyncState {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SyncState($$parsedSource as Partial<SyncState>);
    }
}

/**
 * ToolReport represents statistics for a single tool on the target day
 */
export class ToolReport {
    /**
     * Hook-browser tool name (e.g., "claude", "codex", "opencode")
     */
    "tool_name": string;

    /**
     * Statistics for the single day
     */
    "details": DayDetails;

    /** Creates a new ToolReport instance. */
    constructor($$source: Partial<ToolReport> = {}) {
        if (!("tool_name" in $$source)) {
            this["tool_name"] = "";
        }
        if (!("details" in $$source)) {
            this["details"] = (new DayDetails());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ToolReport instance from a string or object.
     */
    static createFrom($$source: any = {}): ToolReport {
        const $$createField1_0 = $$createType16;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("details" in $$parsedSource) {
            $$parsedSource["details"] = $$createField1_0($$parsedSource["details"]);
        }
        return new ToolReport($$parsedSource as Partial<ToolReport>);
    }
}

/**
 * ToolUsageItem represents a tool used within events
 */
export class ToolUsageItem {
    "tool_name": string;
    "count": number;

    /** Creates a new ToolUsageItem instance. */
    constructor($$source: Partial<ToolUsageItem> = {}) {
        if (!("tool_name" in $$source)) {
            this["tool_name"] = "";
        }
        if (!("count" in $$source)) {
            this["count"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ToolUsageItem instance from a string or object.
     */
    static createFrom($$source: any = {}): ToolUsageItem {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ToolUsageItem($$parsedSource as Partial<ToolUsageItem>);
    }
}

/**
 * User represents a user from the server
 */
export class User {
    "id": number;
    "email": string;
    "name": string;
    "role": string;
    "tenant_id": number;
    "created_at": time$0.Time;
    "updated_at": time$0.Time;

    /** Creates a new User instance. */
    constructor($$source: Partial<User> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("email" in $$source)) {
            this["email"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("role" in $$source)) {
            this["role"] = "";
        }
        if (!("tenant_id" in $$source)) {
            this["tenant_id"] = 0;
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = null;
        }
        if (!("updated_at" in $$source)) {
            this["updated_at"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new User instance from a string or object.
     */
    static createFrom($$source: any = {}): User {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new User($$parsedSource as Partial<User>);
    }
}

export class installRequest {
    "directory": string;
    "repo_owner": string;
    "repo_name": string;
    "repo_branch": string;

    /** Creates a new installRequest instance. */
    constructor($$source: Partial<installRequest> = {}) {
        if (!("directory" in $$source)) {
            this["directory"] = "";
        }
        if (!("repo_owner" in $$source)) {
            this["repo_owner"] = "";
        }
        if (!("repo_name" in $$source)) {
            this["repo_name"] = "";
        }
        if (!("repo_branch" in $$source)) {
            this["repo_branch"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new installRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): installRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new installRequest($$parsedSource as Partial<installRequest>);
    }
}

export class skillRepoConfig {
    "owner": string;
    "name": string;
    "branch": string;
    "enabled": boolean;

    /** Creates a new skillRepoConfig instance. */
    constructor($$source: Partial<skillRepoConfig> = {}) {
        if (!("owner" in $$source)) {
            this["owner"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("branch" in $$source)) {
            this["branch"] = "";
        }
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new skillRepoConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): skillRepoConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new skillRepoConfig($$parsedSource as Partial<skillRepoConfig>);
    }
}

// Private type creation functions
const $$createType0 = AppSettings.createFrom;
const $$createType1 = ServerConfig.createFrom;
const $$createType2 = SyncState.createFrom;
const $$createType3 = User.createFrom;
const $$createType4 = ConfigImportStatus.createFrom;
const $$createType5 = ToolReport.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = SessionStats.createFrom;
const $$createType8 = $Create.Map($Create.Any, $Create.Any);
const $$createType9 = ToolUsageItem.createFrom;
const $$createType10 = $Create.Array($$createType9);
const $$createType11 = PromptStats.createFrom;
const $$createType12 = $Create.Array($Create.Any);
const $$createType13 = $Create.Map($Create.Any, $Create.Any);
const $$createType14 = SessionInfo.createFrom;
const $$createType15 = $Create.Array($$createType14);
const $$createType16 = DayDetails.createFrom;
