// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * PermissionService handles permission checks for the member client
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * CanEditSettings checks if the user can edit provider settings
 * Only managers/admins can edit settings
 */
export function CanEditSettings(): $CancellablePromise<boolean> {
    return $Call.ByID(2115186272);
}

/**
 * CanPushMasterCopy checks if the user can push local settings to server as master copy
 * Only managers/admins can push master copy
 */
export function CanPushMasterCopy(): $CancellablePromise<boolean> {
    return $Call.ByID(2996302654);
}

/**
 * EnsureAdmin returns an error if the user is not an admin
 * This is a convenience method for use in other services
 */
export function EnsureAdmin(): $CancellablePromise<void> {
    return $Call.ByID(238727466);
}

/**
 * GetUserRole returns the current user's role
 */
export function GetUserRole(): $CancellablePromise<string> {
    return $Call.ByID(4274616920);
}

/**
 * IsAdmin checks if the current user has admin (manager) role
 */
export function IsAdmin(): $CancellablePromise<boolean> {
    return $Call.ByID(2751964488);
}

/**
 * Start initializes the permission service
 */
export function Start(): $CancellablePromise<void> {
    return $Call.ByID(3846531371);
}

/**
 * Stop stops the permission service
 */
export function Stop(): $CancellablePromise<void> {
    return $Call.ByID(671573145);
}
