// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ListEnabledProviderNames returns names of enabled providers for a given platform
 * If platform is empty, returns enabled providers from all platforms
 */
export function ListEnabledProviderNames(platform: string): $CancellablePromise<string[]> {
    return $Call.ByID(2681017851, platform).then(($result: any) => {
        return $$createType0($result);
    });
}

export function LoadProviders(kind: string): $CancellablePromise<$models.Provider[]> {
    return $Call.ByID(3413098935, kind).then(($result: any) => {
        return $$createType2($result);
    });
}

export function ReplaceProviders(kind: string, providers: $models.Provider[]): $CancellablePromise<void> {
    return $Call.ByID(1150123249, kind, providers);
}

export function SaveProviders(kind: string, providers: $models.Provider[]): $CancellablePromise<void> {
    return $Call.ByID(1034860836, kind, providers);
}

export function Start(): $CancellablePromise<void> {
    return $Call.ByID(194327613);
}

export function Stop(): $CancellablePromise<void> {
    return $Call.ByID(291391407);
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = $models.Provider.createFrom;
const $$createType2 = $Create.Array($$createType1);
