// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ReportService generates daily activity reports from hook events database
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GenerateDailyReport creates a summary report for a specific date
 * For past dates, attempts to load from cache before generating from database.
 * Today's reports are always generated fresh from the database.
 */
export function GenerateDailyReport(dateStr: string, toolName: string): $CancellablePromise<$models.DailyReport | null> {
    return $Call.ByID(2170137330, dateStr, toolName).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = $models.DailyReport.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
