// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ServerConfigService manages server connection settings
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * GetServerURL returns the configured server URL
 */
export function GetServerURL(): $CancellablePromise<string> {
    return $Call.ByID(1612343823);
}

/**
 * SetServerURL saves the server URL
 */
export function SetServerURL(url: string): $CancellablePromise<void> {
    return $Call.ByID(3189731547, url);
}

/**
 * TestConnection attempts to connect to the configured server
 * If url is provided, it will be used; otherwise, the saved URL will be used
 */
export function TestConnection(url: string): $CancellablePromise<void> {
    return $Call.ByID(2722257435, url);
}
