// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function AddRepo(repo: $models.skillRepoConfig): $CancellablePromise<$models.skillRepoConfig[]> {
    return $Call.ByID(2020364064, repo).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * InstallSkill installs a skill directory from the configured repositories.
 */
export function InstallSkill(req: $models.installRequest): $CancellablePromise<void> {
    return $Call.ByID(2924128557, req);
}

export function ListRepos(): $CancellablePromise<$models.skillRepoConfig[]> {
    return $Call.ByID(1704737214).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * ListSkills aggregates skills from configured repositories and the local install directory.
 */
export function ListSkills(): $CancellablePromise<$models.Skill[]> {
    return $Call.ByID(3387382203).then(($result: any) => {
        return $$createType3($result);
    });
}

export function RemoveRepo(owner: string, name: string): $CancellablePromise<$models.skillRepoConfig[]> {
    return $Call.ByID(2067147157, owner, name).then(($result: any) => {
        return $$createType1($result);
    });
}

export function UninstallSkill(directory: string): $CancellablePromise<void> {
    return $Call.ByID(3488362258, directory);
}

// Private type creation functions
const $$createType0 = $models.skillRepoConfig.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $models.Skill.createFrom;
const $$createType3 = $Create.Array($$createType2);
