// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * UsageSyncService handles synchronization of usage statistics to the server
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * DeleteAllLocalUsageData deletes ALL records from request_log table
 * This is used during logout to clean up all local usage data
 */
export function DeleteAllLocalUsageData(): $CancellablePromise<number> {
    return $Call.ByID(1040438588);
}

/**
 * DeleteOldRecords removes synced records older than retentionDays
 * This is called automatically after each sync to keep the database size manageable
 */
export function DeleteOldRecords(): $CancellablePromise<number> {
    return $Call.ByID(2533702370);
}

/**
 * GetPendingRecordCount returns the number of pending (unsynced) records
 */
export function GetPendingRecordCount(): $CancellablePromise<number> {
    return $Call.ByID(2843833537);
}

/**
 * MarkRecordsAsSynced marks specific records as synced
 */
export function MarkRecordsAsSynced(ids: number[]): $CancellablePromise<void> {
    return $Call.ByID(2647834387, ids);
}

/**
 * SyncUsageStats synchronizes pending usage records to the server
 */
export function SyncUsageStats(): $CancellablePromise<number> {
    return $Call.ByID(3779321181);
}
