// Copyright (c) 2025 AI Together
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package config

import (
	"log"
	"os"
	"strconv"

	_ "github.com/joho/godotenv/autoload"
)

// ProductionLicensePublicKey is the hardcoded public key for license validation
// Uses Ed25519 for signature verification
// Generated by: go run server/scripts/keygen/main.go -genkeys
const ProductionLicensePublicKey = "mGsRA4OXWtkdy5bAJGL/VMlUlMpmrTc/pP5YPfoEbJE="

type Config struct {
	Port             int    `json:"port"`
	JWTSecret        string `json:"jwt_secret"`
	DatabaseURL      string `json:"database_url"`
	Debug            bool   `json:"debug"`
	LicensePublicKey string `json:"license_public_key"`
}

func LoadConfig() *Config {
	// .env is automatically loaded by the import above
	port, err := strconv.Atoi(getEnv("PORT", "9080"))
	if err != nil {
		port = 9080
	}

	dbURL := getEnv("DATABASE_URL", "")
	if dbURL == "" {
		log.Println("Warning: DATABASE_URL not set, using default")
		dbURL = "postgres://localhost:5432/codetogether?sslmode=disable"
	}

	cfg := &Config{
		Port:        port,
		JWTSecret:   getEnv("JWT_SECRET", "default_secret_key_for_development"),
		DatabaseURL: dbURL,
		Debug:       getEnv("DEBUG", "false") == "true",
	}

	// License public key: hardcoded by default, env override only in debug mode
	cfg.LicensePublicKey = ProductionLicensePublicKey
	if cfg.Debug {
		if envKey := getEnv("LICENSE_PUBLIC_KEY", ""); envKey != "" {
			cfg.LicensePublicKey = envKey
		}
	}

	return cfg
}

func getEnv(key, defaultValue string) string {
	if value := os.Getenv(key); value != "" {
		return value
	}
	return defaultValue
}
