// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: license.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countTenantProvidersByKind = `-- name: CountTenantProvidersByKind :one
SELECT COUNT(*) FROM providers p
JOIN teams t ON p.team_id = t.id
WHERE t.tenant_id = $1 AND p.kind = $2
`

type CountTenantProvidersByKindParams struct {
	TenantID int64  `json:"tenantId"`
	Kind     string `json:"kind"`
}

func (q *Queries) CountTenantProvidersByKind(ctx context.Context, arg CountTenantProvidersByKindParams) (int64, error) {
	row := q.db.QueryRow(ctx, countTenantProvidersByKind, arg.TenantID, arg.Kind)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTenantTeams = `-- name: CountTenantTeams :one
SELECT COUNT(*) FROM teams WHERE tenant_id = $1
`

func (q *Queries) CountTenantTeams(ctx context.Context, tenantID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countTenantTeams, tenantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTenantUsers = `-- name: CountTenantUsers :one
SELECT COUNT(*) FROM users WHERE tenant_id = $1
`

func (q *Queries) CountTenantUsers(ctx context.Context, tenantID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countTenantUsers, tenantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getAllLicenses = `-- name: GetAllLicenses :many
SELECT id, license_tier, license_seats, license_key, license_issued_at, license_expires_at, license_id, name,
       license_type, license_max_seats, license_max_teams, license_data_retention_days
FROM tenants
`

type GetAllLicensesRow struct {
	ID                       int64            `json:"id"`
	LicenseTier              pgtype.Text      `json:"licenseTier"`
	LicenseSeats             pgtype.Int4      `json:"licenseSeats"`
	LicenseKey               pgtype.Text      `json:"licenseKey"`
	LicenseIssuedAt          pgtype.Timestamp `json:"licenseIssuedAt"`
	LicenseExpiresAt         pgtype.Timestamp `json:"licenseExpiresAt"`
	LicenseID                pgtype.Text      `json:"licenseId"`
	Name                     string           `json:"name"`
	LicenseType              pgtype.Text      `json:"licenseType"`
	LicenseMaxSeats          pgtype.Int4      `json:"licenseMaxSeats"`
	LicenseMaxTeams          pgtype.Int4      `json:"licenseMaxTeams"`
	LicenseDataRetentionDays pgtype.Int4      `json:"licenseDataRetentionDays"`
}

func (q *Queries) GetAllLicenses(ctx context.Context) ([]GetAllLicensesRow, error) {
	rows, err := q.db.Query(ctx, getAllLicenses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAllLicensesRow{}
	for rows.Next() {
		var i GetAllLicensesRow
		if err := rows.Scan(
			&i.ID,
			&i.LicenseTier,
			&i.LicenseSeats,
			&i.LicenseKey,
			&i.LicenseIssuedAt,
			&i.LicenseExpiresAt,
			&i.LicenseID,
			&i.Name,
			&i.LicenseType,
			&i.LicenseMaxSeats,
			&i.LicenseMaxTeams,
			&i.LicenseDataRetentionDays,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProviderCountsByKind = `-- name: GetProviderCountsByKind :many
SELECT p.kind, COUNT(*) as count FROM providers p
JOIN teams t ON p.team_id = t.id
WHERE t.tenant_id = $1
GROUP BY p.kind
`

type GetProviderCountsByKindRow struct {
	Kind  string `json:"kind"`
	Count int64  `json:"count"`
}

func (q *Queries) GetProviderCountsByKind(ctx context.Context, tenantID int64) ([]GetProviderCountsByKindRow, error) {
	rows, err := q.db.Query(ctx, getProviderCountsByKind, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetProviderCountsByKindRow{}
	for rows.Next() {
		var i GetProviderCountsByKindRow
		if err := rows.Scan(&i.Kind, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTenantLicense = `-- name: GetTenantLicense :one
SELECT license_tier, license_seats, license_key, license_issued_at, license_expires_at, license_id, name,
       license_type, license_max_seats, license_max_teams, license_data_retention_days
FROM tenants WHERE id = $1
`

type GetTenantLicenseRow struct {
	LicenseTier              pgtype.Text      `json:"licenseTier"`
	LicenseSeats             pgtype.Int4      `json:"licenseSeats"`
	LicenseKey               pgtype.Text      `json:"licenseKey"`
	LicenseIssuedAt          pgtype.Timestamp `json:"licenseIssuedAt"`
	LicenseExpiresAt         pgtype.Timestamp `json:"licenseExpiresAt"`
	LicenseID                pgtype.Text      `json:"licenseId"`
	Name                     string           `json:"name"`
	LicenseType              pgtype.Text      `json:"licenseType"`
	LicenseMaxSeats          pgtype.Int4      `json:"licenseMaxSeats"`
	LicenseMaxTeams          pgtype.Int4      `json:"licenseMaxTeams"`
	LicenseDataRetentionDays pgtype.Int4      `json:"licenseDataRetentionDays"`
}

func (q *Queries) GetTenantLicense(ctx context.Context, id int64) (GetTenantLicenseRow, error) {
	row := q.db.QueryRow(ctx, getTenantLicense, id)
	var i GetTenantLicenseRow
	err := row.Scan(
		&i.LicenseTier,
		&i.LicenseSeats,
		&i.LicenseKey,
		&i.LicenseIssuedAt,
		&i.LicenseExpiresAt,
		&i.LicenseID,
		&i.Name,
		&i.LicenseType,
		&i.LicenseMaxSeats,
		&i.LicenseMaxTeams,
		&i.LicenseDataRetentionDays,
	)
	return i, err
}

const updateTenantLicense = `-- name: UpdateTenantLicense :exec
UPDATE tenants SET
    license_id = $2,
    license_tier = $3,
    license_seats = $4,
    license_key = $5,
    license_issued_at = $6,
    license_expires_at = $7,
    license_type = $8,
    license_max_seats = $9,
    license_max_teams = $10,
    license_data_retention_days = $11,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
`

type UpdateTenantLicenseParams struct {
	ID                       int64            `json:"id"`
	LicenseID                pgtype.Text      `json:"licenseId"`
	LicenseTier              pgtype.Text      `json:"licenseTier"`
	LicenseSeats             pgtype.Int4      `json:"licenseSeats"`
	LicenseKey               pgtype.Text      `json:"licenseKey"`
	LicenseIssuedAt          pgtype.Timestamp `json:"licenseIssuedAt"`
	LicenseExpiresAt         pgtype.Timestamp `json:"licenseExpiresAt"`
	LicenseType              pgtype.Text      `json:"licenseType"`
	LicenseMaxSeats          pgtype.Int4      `json:"licenseMaxSeats"`
	LicenseMaxTeams          pgtype.Int4      `json:"licenseMaxTeams"`
	LicenseDataRetentionDays pgtype.Int4      `json:"licenseDataRetentionDays"`
}

func (q *Queries) UpdateTenantLicense(ctx context.Context, arg UpdateTenantLicenseParams) error {
	_, err := q.db.Exec(ctx, updateTenantLicense,
		arg.ID,
		arg.LicenseID,
		arg.LicenseTier,
		arg.LicenseSeats,
		arg.LicenseKey,
		arg.LicenseIssuedAt,
		arg.LicenseExpiresAt,
		arg.LicenseType,
		arg.LicenseMaxSeats,
		arg.LicenseMaxTeams,
		arg.LicenseDataRetentionDays,
	)
	return err
}
