// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Provider struct {
	ID              int64            `json:"id"`
	Name            string           `json:"name"`
	ApiUrl          string           `json:"apiUrl"`
	ApiKey          string           `json:"apiKey"`
	TeamID          int64            `json:"teamId"`
	Kind            string           `json:"kind"`
	Enabled         pgtype.Bool      `json:"enabled"`
	ModelMapping    []byte           `json:"modelMapping"`
	SupportedModels []byte           `json:"supportedModels"`
	Level           pgtype.Int4      `json:"level"`
	CreatedAt       pgtype.Timestamp `json:"createdAt"`
	UpdatedAt       pgtype.Timestamp `json:"updatedAt"`
}

type RelayToken struct {
	ID          int64            `json:"id"`
	TokenHash   string           `json:"tokenHash"`
	UserID      int64            `json:"userId"`
	TenantID    int64            `json:"tenantId"`
	TokenPrefix string           `json:"tokenPrefix"`
	CreatedAt   pgtype.Timestamp `json:"createdAt"`
	LastUsedAt  pgtype.Timestamp `json:"lastUsedAt"`
	RevokedAt   pgtype.Timestamp `json:"revokedAt"`
}

type RequestLog struct {
	ID                int64            `json:"id"`
	Platform          pgtype.Text      `json:"platform"`
	Model             pgtype.Text      `json:"model"`
	Provider          pgtype.Text      `json:"provider"`
	HttpCode          pgtype.Int4      `json:"httpCode"`
	InputTokens       pgtype.Int4      `json:"inputTokens"`
	OutputTokens      pgtype.Int4      `json:"outputTokens"`
	CacheCreateTokens pgtype.Int4      `json:"cacheCreateTokens"`
	CacheReadTokens   pgtype.Int4      `json:"cacheReadTokens"`
	ReasoningTokens   pgtype.Int4      `json:"reasoningTokens"`
	IsStream          pgtype.Bool      `json:"isStream"`
	DurationSec       pgtype.Float4    `json:"durationSec"`
	TenantID          int64            `json:"tenantId"`
	UserID            int64            `json:"userId"`
	CreatedAt         pgtype.Timestamp `json:"createdAt"`
}

type Team struct {
	ID          int64            `json:"id"`
	Name        string           `json:"name"`
	Description pgtype.Text      `json:"description"`
	OwnerID     int64            `json:"ownerId"`
	TenantID    int64            `json:"tenantId"`
	Settings    []byte           `json:"settings"`
	CreatedAt   pgtype.Timestamp `json:"createdAt"`
	UpdatedAt   pgtype.Timestamp `json:"updatedAt"`
}

type TeamMember struct {
	ID        int64            `json:"id"`
	TeamID    int64            `json:"teamId"`
	UserID    int64            `json:"userId"`
	Role      string           `json:"role"`
	CreatedAt pgtype.Timestamp `json:"createdAt"`
	UpdatedAt pgtype.Timestamp `json:"updatedAt"`
}

type TeamUsageSummary struct {
	ID          int64            `json:"id"`
	TeamID      int64            `json:"teamId"`
	PeriodStart pgtype.Timestamp `json:"periodStart"`
	PeriodEnd   pgtype.Timestamp `json:"periodEnd"`
	TotalInput  pgtype.Int4      `json:"totalInput"`
	TotalOutput pgtype.Int4      `json:"totalOutput"`
	TotalCost   pgtype.Numeric   `json:"totalCost"`
	CreatedAt   pgtype.Timestamp `json:"createdAt"`
}

type Tenant struct {
	ID                       int64            `json:"id"`
	Name                     string           `json:"name"`
	Subdomain                pgtype.Text      `json:"subdomain"`
	LicenseID                pgtype.Text      `json:"licenseId"`
	LicenseTier              pgtype.Text      `json:"licenseTier"`
	LicenseSeats             pgtype.Int4      `json:"licenseSeats"`
	LicenseKey               pgtype.Text      `json:"licenseKey"`
	LicenseIssuedAt          pgtype.Timestamp `json:"licenseIssuedAt"`
	LicenseExpiresAt         pgtype.Timestamp `json:"licenseExpiresAt"`
	LicenseType              pgtype.Text      `json:"licenseType"`
	LicenseMaxSeats          pgtype.Int4      `json:"licenseMaxSeats"`
	LicenseMaxTeams          pgtype.Int4      `json:"licenseMaxTeams"`
	LicenseDataRetentionDays pgtype.Int4      `json:"licenseDataRetentionDays"`
	CreatedAt                pgtype.Timestamp `json:"createdAt"`
	UpdatedAt                pgtype.Timestamp `json:"updatedAt"`
}

type User struct {
	ID        int64            `json:"id"`
	Email     string           `json:"email"`
	Name      string           `json:"name"`
	Password  string           `json:"password"`
	Role      string           `json:"role"`
	TenantID  int64            `json:"tenantId"`
	CreatedAt pgtype.Timestamp `json:"createdAt"`
	UpdatedAt pgtype.Timestamp `json:"updatedAt"`
}
