// Copyright (c) 2025 Code Together
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.


// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: providers.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProvider = `-- name: CreateProvider :one
INSERT INTO providers (name, api_url, api_key, team_id, enabled, kind, model_mapping, supported_models, level)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, name, api_url, api_key, team_id, kind, enabled, model_mapping, supported_models, level, created_at, updated_at
`

type CreateProviderParams struct {
	Name            string      `json:"name"`
	ApiUrl          string      `json:"apiUrl"`
	ApiKey          string      `json:"apiKey"`
	TeamID          int64       `json:"teamId"`
	Enabled         pgtype.Bool `json:"enabled"`
	Kind            string      `json:"kind"`
	ModelMapping    []byte      `json:"modelMapping"`
	SupportedModels []byte      `json:"supportedModels"`
	Level           pgtype.Int4 `json:"level"`
}

func (q *Queries) CreateProvider(ctx context.Context, arg CreateProviderParams) (Provider, error) {
	row := q.db.QueryRow(ctx, createProvider,
		arg.Name,
		arg.ApiUrl,
		arg.ApiKey,
		arg.TeamID,
		arg.Enabled,
		arg.Kind,
		arg.ModelMapping,
		arg.SupportedModels,
		arg.Level,
	)
	var i Provider
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ApiUrl,
		&i.ApiKey,
		&i.TeamID,
		&i.Kind,
		&i.Enabled,
		&i.ModelMapping,
		&i.SupportedModels,
		&i.Level,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProvider = `-- name: DeleteProvider :exec
DELETE FROM providers WHERE id = $1
`

func (q *Queries) DeleteProvider(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteProvider, id)
	return err
}

const disableProvider = `-- name: DisableProvider :exec
UPDATE providers SET enabled = false WHERE id = $1
`

func (q *Queries) DisableProvider(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, disableProvider, id)
	return err
}

const enableProvider = `-- name: EnableProvider :exec
UPDATE providers SET enabled = true WHERE id = $1
`

func (q *Queries) EnableProvider(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, enableProvider, id)
	return err
}

const getProviderByID = `-- name: GetProviderByID :one
SELECT id, name, api_url, api_key, team_id, kind, enabled, model_mapping, supported_models, level, created_at, updated_at
FROM providers
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetProviderByID(ctx context.Context, id int64) (Provider, error) {
	row := q.db.QueryRow(ctx, getProviderByID, id)
	var i Provider
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ApiUrl,
		&i.ApiKey,
		&i.TeamID,
		&i.Kind,
		&i.Enabled,
		&i.ModelMapping,
		&i.SupportedModels,
		&i.Level,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProvidersByTeamID = `-- name: GetProvidersByTeamID :many
SELECT id, name, api_url, api_key, team_id, kind, enabled, model_mapping, supported_models, level, created_at, updated_at
FROM providers
WHERE team_id = $1
`

func (q *Queries) GetProvidersByTeamID(ctx context.Context, teamID int64) ([]Provider, error) {
	rows, err := q.db.Query(ctx, getProvidersByTeamID, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Provider{}
	for rows.Next() {
		var i Provider
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ApiUrl,
			&i.ApiKey,
			&i.TeamID,
			&i.Kind,
			&i.Enabled,
			&i.ModelMapping,
			&i.SupportedModels,
			&i.Level,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProvider = `-- name: UpdateProvider :exec
UPDATE providers
SET name = $2, api_url = $3, api_key = $4, enabled = $5, kind = $6, model_mapping = $7, supported_models = $8, level = $9, updated_at = CURRENT_TIMESTAMP
WHERE id = $1
`

type UpdateProviderParams struct {
	ID              int64       `json:"id"`
	Name            string      `json:"name"`
	ApiUrl          string      `json:"apiUrl"`
	ApiKey          string      `json:"apiKey"`
	Enabled         pgtype.Bool `json:"enabled"`
	Kind            string      `json:"kind"`
	ModelMapping    []byte      `json:"modelMapping"`
	SupportedModels []byte      `json:"supportedModels"`
	Level           pgtype.Int4 `json:"level"`
}

func (q *Queries) UpdateProvider(ctx context.Context, arg UpdateProviderParams) error {
	_, err := q.db.Exec(ctx, updateProvider,
		arg.ID,
		arg.Name,
		arg.ApiUrl,
		arg.ApiKey,
		arg.Enabled,
		arg.Kind,
		arg.ModelMapping,
		arg.SupportedModels,
		arg.Level,
	)
	return err
}
