// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	AddTeamMember(ctx context.Context, arg AddTeamMemberParams) error
	CountTenantProvidersByKind(ctx context.Context, arg CountTenantProvidersByKindParams) (int64, error)
	CountTenantTeams(ctx context.Context, tenantID int64) (int64, error)
	CountTenantUsers(ctx context.Context, tenantID int64) (int64, error)
	CreateProvider(ctx context.Context, arg CreateProviderParams) (Provider, error)
	CreateRelayToken(ctx context.Context, arg CreateRelayTokenParams) (RelayToken, error)
	CreateTeam(ctx context.Context, arg CreateTeamParams) (Team, error)
	CreateTeamUsageSummary(ctx context.Context, arg CreateTeamUsageSummaryParams) error
	CreateUsageRecord(ctx context.Context, arg CreateUsageRecordParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) error
	DeleteProvider(ctx context.Context, id int64) error
	DeleteTeam(ctx context.Context, id int64) error
	DisableProvider(ctx context.Context, id int64) error
	EnableProvider(ctx context.Context, id int64) error
	GetAllLicenses(ctx context.Context) ([]GetAllLicensesRow, error)
	GetProviderByID(ctx context.Context, id int64) (Provider, error)
	GetProviderCountsByKind(ctx context.Context, tenantID int64) ([]GetProviderCountsByKindRow, error)
	GetProvidersByTeamID(ctx context.Context, teamID int64) ([]Provider, error)
	GetRelayTokenByHash(ctx context.Context, tokenHash string) (RelayToken, error)
	GetRelayTokenByUserID(ctx context.Context, userID int64) (RelayToken, error)
	GetTeamByID(ctx context.Context, id int64) (Team, error)
	GetTeamMembers(ctx context.Context, teamID int64) ([]GetTeamMembersRow, error)
	GetTeamUsageSummary(ctx context.Context, arg GetTeamUsageSummaryParams) ([]GetTeamUsageSummaryRow, error)
	GetTeamsByUserID(ctx context.Context, userID int64) ([]GetTeamsByUserIDRow, error)
	GetTenantLicense(ctx context.Context, id int64) (GetTenantLicenseRow, error)
	GetUsageByTeamIDAndPeriod(ctx context.Context, arg GetUsageByTeamIDAndPeriodParams) ([]RequestLog, error)
	GetUsageByUserIDAndPeriod(ctx context.Context, arg GetUsageByUserIDAndPeriodParams) ([]RequestLog, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id int64) (User, error)
	RemoveTeamMember(ctx context.Context, arg RemoveTeamMemberParams) error
	RevokeRelayTokenByUserID(ctx context.Context, userID int64) error
	UpdateProvider(ctx context.Context, arg UpdateProviderParams) error
	UpdateRelayTokenLastUsed(ctx context.Context, id int64) error
	UpdateTeam(ctx context.Context, arg UpdateTeamParams) error
	UpdateTenantLicense(ctx context.Context, arg UpdateTenantLicenseParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) error
}

var _ Querier = (*Queries)(nil)
