// Copyright (c) 2025 Code Together
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	AddTeamMember(ctx context.Context, arg AddTeamMemberParams) error
	CountTenantProvidersByKind(ctx context.Context, arg CountTenantProvidersByKindParams) (int64, error)
	CountTenantTeams(ctx context.Context, tenantID int64) (int64, error)
	CountTenantUsers(ctx context.Context, tenantID int64) (int64, error)
	CreateProvider(ctx context.Context, arg CreateProviderParams) (Provider, error)
	CreateTeam(ctx context.Context, arg CreateTeamParams) (Team, error)
	CreateTeamUsageSummary(ctx context.Context, arg CreateTeamUsageSummaryParams) error
	CreateUsageRecord(ctx context.Context, arg CreateUsageRecordParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) error
	DeleteProvider(ctx context.Context, id int64) error
	DeleteTeam(ctx context.Context, id int64) error
	DisableProvider(ctx context.Context, id int64) error
	EnableProvider(ctx context.Context, id int64) error
	GetAllLicenses(ctx context.Context) ([]GetAllLicensesRow, error)
	GetProviderByID(ctx context.Context, id int64) (Provider, error)
	GetProviderCountsByKind(ctx context.Context, tenantID int64) ([]GetProviderCountsByKindRow, error)
	GetProvidersByTeamID(ctx context.Context, teamID int64) ([]Provider, error)
	GetTeamByID(ctx context.Context, id int64) (Team, error)
	GetTeamMembers(ctx context.Context, teamID int64) ([]GetTeamMembersRow, error)
	GetTeamUsageSummary(ctx context.Context, arg GetTeamUsageSummaryParams) ([]GetTeamUsageSummaryRow, error)
	GetTeamsByUserID(ctx context.Context, userID int64) ([]GetTeamsByUserIDRow, error)
	GetTenantLicense(ctx context.Context, id int64) (GetTenantLicenseRow, error)
	GetUsageByTeamIDAndPeriod(ctx context.Context, arg GetUsageByTeamIDAndPeriodParams) ([]RequestLog, error)
	GetUsageByUserIDAndPeriod(ctx context.Context, arg GetUsageByUserIDAndPeriodParams) ([]RequestLog, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id int64) (User, error)
	RemoveTeamMember(ctx context.Context, arg RemoveTeamMemberParams) error
	UpdateProvider(ctx context.Context, arg UpdateProviderParams) error
	UpdateTeam(ctx context.Context, arg UpdateTeamParams) error
	UpdateTenantLicense(ctx context.Context, arg UpdateTenantLicenseParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) error
}

var _ Querier = (*Queries)(nil)
