// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: relay_tokens.sql

package db

import (
	"context"
)

const createRelayToken = `-- name: CreateRelayToken :one
INSERT INTO relay_tokens (token_hash, user_id, tenant_id, token_prefix)
VALUES ($1, $2, $3, $4)
RETURNING id, token_hash, user_id, tenant_id, token_prefix, created_at, last_used_at, revoked_at
`

type CreateRelayTokenParams struct {
	TokenHash   string `json:"tokenHash"`
	UserID      int64  `json:"userId"`
	TenantID    int64  `json:"tenantId"`
	TokenPrefix string `json:"tokenPrefix"`
}

func (q *Queries) CreateRelayToken(ctx context.Context, arg CreateRelayTokenParams) (RelayToken, error) {
	row := q.db.QueryRow(ctx, createRelayToken,
		arg.TokenHash,
		arg.UserID,
		arg.TenantID,
		arg.TokenPrefix,
	)
	var i RelayToken
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.UserID,
		&i.TenantID,
		&i.TokenPrefix,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getRelayTokenByHash = `-- name: GetRelayTokenByHash :one
SELECT id, token_hash, user_id, tenant_id, token_prefix, created_at, last_used_at, revoked_at
FROM relay_tokens
WHERE token_hash = $1 AND revoked_at IS NULL
`

func (q *Queries) GetRelayTokenByHash(ctx context.Context, tokenHash string) (RelayToken, error) {
	row := q.db.QueryRow(ctx, getRelayTokenByHash, tokenHash)
	var i RelayToken
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.UserID,
		&i.TenantID,
		&i.TokenPrefix,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getRelayTokenByUserID = `-- name: GetRelayTokenByUserID :one
SELECT id, token_hash, user_id, tenant_id, token_prefix, created_at, last_used_at, revoked_at
FROM relay_tokens
WHERE user_id = $1 AND revoked_at IS NULL
`

func (q *Queries) GetRelayTokenByUserID(ctx context.Context, userID int64) (RelayToken, error) {
	row := q.db.QueryRow(ctx, getRelayTokenByUserID, userID)
	var i RelayToken
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.UserID,
		&i.TenantID,
		&i.TokenPrefix,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const revokeRelayTokenByUserID = `-- name: RevokeRelayTokenByUserID :exec
UPDATE relay_tokens
SET revoked_at = CURRENT_TIMESTAMP
WHERE user_id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeRelayTokenByUserID(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, revokeRelayTokenByUserID, userID)
	return err
}

const updateRelayTokenLastUsed = `-- name: UpdateRelayTokenLastUsed :exec
UPDATE relay_tokens
SET last_used_at = CURRENT_TIMESTAMP
WHERE id = $1
`

func (q *Queries) UpdateRelayTokenLastUsed(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, updateRelayTokenLastUsed, id)
	return err
}
