// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: usage.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTeamUsageSummary = `-- name: CreateTeamUsageSummary :exec
INSERT INTO team_usage_summary (team_id, period_start, period_end, total_input, total_output, total_cost)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateTeamUsageSummaryParams struct {
	TeamID      int64            `json:"teamId"`
	PeriodStart pgtype.Timestamp `json:"periodStart"`
	PeriodEnd   pgtype.Timestamp `json:"periodEnd"`
	TotalInput  pgtype.Int4      `json:"totalInput"`
	TotalOutput pgtype.Int4      `json:"totalOutput"`
	TotalCost   pgtype.Numeric   `json:"totalCost"`
}

func (q *Queries) CreateTeamUsageSummary(ctx context.Context, arg CreateTeamUsageSummaryParams) error {
	_, err := q.db.Exec(ctx, createTeamUsageSummary,
		arg.TeamID,
		arg.PeriodStart,
		arg.PeriodEnd,
		arg.TotalInput,
		arg.TotalOutput,
		arg.TotalCost,
	)
	return err
}

const createUsageRecord = `-- name: CreateUsageRecord :exec
INSERT INTO request_log (platform, model, provider, http_code, input_tokens, output_tokens, cache_create_tokens, cache_read_tokens, reasoning_tokens, is_stream, duration_sec, tenant_id, user_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
`

type CreateUsageRecordParams struct {
	Platform          pgtype.Text   `json:"platform"`
	Model             pgtype.Text   `json:"model"`
	Provider          pgtype.Text   `json:"provider"`
	HttpCode          pgtype.Int4   `json:"httpCode"`
	InputTokens       pgtype.Int4   `json:"inputTokens"`
	OutputTokens      pgtype.Int4   `json:"outputTokens"`
	CacheCreateTokens pgtype.Int4   `json:"cacheCreateTokens"`
	CacheReadTokens   pgtype.Int4   `json:"cacheReadTokens"`
	ReasoningTokens   pgtype.Int4   `json:"reasoningTokens"`
	IsStream          pgtype.Bool   `json:"isStream"`
	DurationSec       pgtype.Float4 `json:"durationSec"`
	TenantID          int64         `json:"tenantId"`
	UserID            int64         `json:"userId"`
}

func (q *Queries) CreateUsageRecord(ctx context.Context, arg CreateUsageRecordParams) error {
	_, err := q.db.Exec(ctx, createUsageRecord,
		arg.Platform,
		arg.Model,
		arg.Provider,
		arg.HttpCode,
		arg.InputTokens,
		arg.OutputTokens,
		arg.CacheCreateTokens,
		arg.CacheReadTokens,
		arg.ReasoningTokens,
		arg.IsStream,
		arg.DurationSec,
		arg.TenantID,
		arg.UserID,
	)
	return err
}

const getTeamUsageSummary = `-- name: GetTeamUsageSummary :many
SELECT team_id, period_start, period_end, total_input, total_output, total_cost, created_at
FROM team_usage_summary
WHERE team_id = $1
  AND period_start >= $2
  AND period_end <= $3
ORDER BY period_start DESC
`

type GetTeamUsageSummaryParams struct {
	TeamID      int64            `json:"teamId"`
	PeriodStart pgtype.Timestamp `json:"periodStart"`
	PeriodEnd   pgtype.Timestamp `json:"periodEnd"`
}

type GetTeamUsageSummaryRow struct {
	TeamID      int64            `json:"teamId"`
	PeriodStart pgtype.Timestamp `json:"periodStart"`
	PeriodEnd   pgtype.Timestamp `json:"periodEnd"`
	TotalInput  pgtype.Int4      `json:"totalInput"`
	TotalOutput pgtype.Int4      `json:"totalOutput"`
	TotalCost   pgtype.Numeric   `json:"totalCost"`
	CreatedAt   pgtype.Timestamp `json:"createdAt"`
}

func (q *Queries) GetTeamUsageSummary(ctx context.Context, arg GetTeamUsageSummaryParams) ([]GetTeamUsageSummaryRow, error) {
	rows, err := q.db.Query(ctx, getTeamUsageSummary, arg.TeamID, arg.PeriodStart, arg.PeriodEnd)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTeamUsageSummaryRow{}
	for rows.Next() {
		var i GetTeamUsageSummaryRow
		if err := rows.Scan(
			&i.TeamID,
			&i.PeriodStart,
			&i.PeriodEnd,
			&i.TotalInput,
			&i.TotalOutput,
			&i.TotalCost,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUsageByTeamIDAndPeriod = `-- name: GetUsageByTeamIDAndPeriod :many
SELECT id, platform, model, provider, http_code, input_tokens, output_tokens, cache_create_tokens, cache_read_tokens, reasoning_tokens, is_stream, duration_sec, tenant_id, user_id, created_at
FROM request_log
WHERE tenant_id = $1
  AND created_at >= $2
  AND created_at <= $3
ORDER BY created_at DESC
`

type GetUsageByTeamIDAndPeriodParams struct {
	TenantID    int64            `json:"tenantId"`
	CreatedAt   pgtype.Timestamp `json:"createdAt"`
	CreatedAt_2 pgtype.Timestamp `json:"createdAt2"`
}

func (q *Queries) GetUsageByTeamIDAndPeriod(ctx context.Context, arg GetUsageByTeamIDAndPeriodParams) ([]RequestLog, error) {
	rows, err := q.db.Query(ctx, getUsageByTeamIDAndPeriod, arg.TenantID, arg.CreatedAt, arg.CreatedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RequestLog{}
	for rows.Next() {
		var i RequestLog
		if err := rows.Scan(
			&i.ID,
			&i.Platform,
			&i.Model,
			&i.Provider,
			&i.HttpCode,
			&i.InputTokens,
			&i.OutputTokens,
			&i.CacheCreateTokens,
			&i.CacheReadTokens,
			&i.ReasoningTokens,
			&i.IsStream,
			&i.DurationSec,
			&i.TenantID,
			&i.UserID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUsageByUserIDAndPeriod = `-- name: GetUsageByUserIDAndPeriod :many
SELECT id, platform, model, provider, http_code, input_tokens, output_tokens, cache_create_tokens, cache_read_tokens, reasoning_tokens, is_stream, duration_sec, tenant_id, user_id, created_at
FROM request_log
WHERE user_id = $1
  AND created_at >= $2
  AND created_at <= $3
ORDER BY created_at DESC
`

type GetUsageByUserIDAndPeriodParams struct {
	UserID      int64            `json:"userId"`
	CreatedAt   pgtype.Timestamp `json:"createdAt"`
	CreatedAt_2 pgtype.Timestamp `json:"createdAt2"`
}

func (q *Queries) GetUsageByUserIDAndPeriod(ctx context.Context, arg GetUsageByUserIDAndPeriodParams) ([]RequestLog, error) {
	rows, err := q.db.Query(ctx, getUsageByUserIDAndPeriod, arg.UserID, arg.CreatedAt, arg.CreatedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RequestLog{}
	for rows.Next() {
		var i RequestLog
		if err := rows.Scan(
			&i.ID,
			&i.Platform,
			&i.Model,
			&i.Provider,
			&i.HttpCode,
			&i.InputTokens,
			&i.OutputTokens,
			&i.CacheCreateTokens,
			&i.CacheReadTokens,
			&i.ReasoningTokens,
			&i.IsStream,
			&i.DurationSec,
			&i.TenantID,
			&i.UserID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
