DROP TABLE IF EXISTS provider_templates CASCADE;
DROP TABLE IF EXISTS team_usage_summary CASCADE;
DROP TABLE IF EXISTS request_log CASCADE;
DROP TABLE IF EXISTS providers CASCADE;
DROP TABLE IF EXISTS team_members CASCADE;
DROP TABLE IF EXISTS teams CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS tenants CASCADE;

