// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../time/models.js";

export class HeatmapStat {
    "day": string;
    "total_requests": number;
    "input_tokens": number;
    "output_tokens": number;
    "reasoning_tokens": number;
    "total_cost": number;

    /** Creates a new HeatmapStat instance. */
    constructor($$source: Partial<HeatmapStat> = {}) {
        if (!("day" in $$source)) {
            this["day"] = "";
        }
        if (!("total_requests" in $$source)) {
            this["total_requests"] = 0;
        }
        if (!("input_tokens" in $$source)) {
            this["input_tokens"] = 0;
        }
        if (!("output_tokens" in $$source)) {
            this["output_tokens"] = 0;
        }
        if (!("reasoning_tokens" in $$source)) {
            this["reasoning_tokens"] = 0;
        }
        if (!("total_cost" in $$source)) {
            this["total_cost"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HeatmapStat instance from a string or object.
     */
    static createFrom($$source: any = {}): HeatmapStat {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new HeatmapStat($$parsedSource as Partial<HeatmapStat>);
    }
}

export class LogStats {
    "total_requests": number;
    "input_tokens": number;
    "output_tokens": number;
    "reasoning_tokens": number;
    "cache_create_tokens": number;
    "cache_read_tokens": number;
    "cost_total": number;
    "cost_input": number;
    "cost_output": number;
    "cost_cache_create": number;
    "cost_cache_read": number;
    "series": LogStatsSeries[];

    /** Creates a new LogStats instance. */
    constructor($$source: Partial<LogStats> = {}) {
        if (!("total_requests" in $$source)) {
            this["total_requests"] = 0;
        }
        if (!("input_tokens" in $$source)) {
            this["input_tokens"] = 0;
        }
        if (!("output_tokens" in $$source)) {
            this["output_tokens"] = 0;
        }
        if (!("reasoning_tokens" in $$source)) {
            this["reasoning_tokens"] = 0;
        }
        if (!("cache_create_tokens" in $$source)) {
            this["cache_create_tokens"] = 0;
        }
        if (!("cache_read_tokens" in $$source)) {
            this["cache_read_tokens"] = 0;
        }
        if (!("cost_total" in $$source)) {
            this["cost_total"] = 0;
        }
        if (!("cost_input" in $$source)) {
            this["cost_input"] = 0;
        }
        if (!("cost_output" in $$source)) {
            this["cost_output"] = 0;
        }
        if (!("cost_cache_create" in $$source)) {
            this["cost_cache_create"] = 0;
        }
        if (!("cost_cache_read" in $$source)) {
            this["cost_cache_read"] = 0;
        }
        if (!("series" in $$source)) {
            this["series"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LogStats instance from a string or object.
     */
    static createFrom($$source: any = {}): LogStats {
        const $$createField11_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("series" in $$parsedSource) {
            $$parsedSource["series"] = $$createField11_0($$parsedSource["series"]);
        }
        return new LogStats($$parsedSource as Partial<LogStats>);
    }
}

export class LogStatsSeries {
    "day": string;
    "total_requests": number;
    "input_tokens": number;
    "output_tokens": number;
    "reasoning_tokens": number;
    "cache_create_tokens": number;
    "cache_read_tokens": number;
    "total_cost": number;

    /** Creates a new LogStatsSeries instance. */
    constructor($$source: Partial<LogStatsSeries> = {}) {
        if (!("day" in $$source)) {
            this["day"] = "";
        }
        if (!("total_requests" in $$source)) {
            this["total_requests"] = 0;
        }
        if (!("input_tokens" in $$source)) {
            this["input_tokens"] = 0;
        }
        if (!("output_tokens" in $$source)) {
            this["output_tokens"] = 0;
        }
        if (!("reasoning_tokens" in $$source)) {
            this["reasoning_tokens"] = 0;
        }
        if (!("cache_create_tokens" in $$source)) {
            this["cache_create_tokens"] = 0;
        }
        if (!("cache_read_tokens" in $$source)) {
            this["cache_read_tokens"] = 0;
        }
        if (!("total_cost" in $$source)) {
            this["total_cost"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LogStatsSeries instance from a string or object.
     */
    static createFrom($$source: any = {}): LogStatsSeries {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LogStatsSeries($$parsedSource as Partial<LogStatsSeries>);
    }
}

export class ProviderDailyStat {
    "provider": string;
    "total_requests": number;
    "successful_requests": number;
    "failed_requests": number;
    "success_rate": number;
    "input_tokens": number;
    "output_tokens": number;
    "reasoning_tokens": number;
    "cache_create_tokens": number;
    "cache_read_tokens": number;
    "cost_total": number;

    /** Creates a new ProviderDailyStat instance. */
    constructor($$source: Partial<ProviderDailyStat> = {}) {
        if (!("provider" in $$source)) {
            this["provider"] = "";
        }
        if (!("total_requests" in $$source)) {
            this["total_requests"] = 0;
        }
        if (!("successful_requests" in $$source)) {
            this["successful_requests"] = 0;
        }
        if (!("failed_requests" in $$source)) {
            this["failed_requests"] = 0;
        }
        if (!("success_rate" in $$source)) {
            this["success_rate"] = 0;
        }
        if (!("input_tokens" in $$source)) {
            this["input_tokens"] = 0;
        }
        if (!("output_tokens" in $$source)) {
            this["output_tokens"] = 0;
        }
        if (!("reasoning_tokens" in $$source)) {
            this["reasoning_tokens"] = 0;
        }
        if (!("cache_create_tokens" in $$source)) {
            this["cache_create_tokens"] = 0;
        }
        if (!("cache_read_tokens" in $$source)) {
            this["cache_read_tokens"] = 0;
        }
        if (!("cost_total" in $$source)) {
            this["cost_total"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProviderDailyStat instance from a string or object.
     */
    static createFrom($$source: any = {}): ProviderDailyStat {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProviderDailyStat($$parsedSource as Partial<ProviderDailyStat>);
    }
}

export class RequestLog {
    "id": number;

    /**
     * claude code or codex
     */
    "platform": string;
    "model": string;

    /**
     * provider name
     */
    "provider": string;
    "http_code": number;
    "input_tokens": number;
    "output_tokens": number;
    "cache_create_tokens": number;
    "cache_read_tokens": number;
    "reasoning_tokens": number;
    "is_stream": boolean;
    "duration_sec": number;
    "created_at": time$0.Time;

    /**
     * whether synced to server
     */
    "synced_to_server": boolean;
    "input_cost": number;
    "output_cost": number;
    "cache_create_cost": number;
    "cache_read_cost": number;
    "ephemeral_5m_cost": number;
    "ephemeral_1h_cost": number;
    "total_cost": number;
    "has_pricing": boolean;

    /** Creates a new RequestLog instance. */
    constructor($$source: Partial<RequestLog> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("platform" in $$source)) {
            this["platform"] = "";
        }
        if (!("model" in $$source)) {
            this["model"] = "";
        }
        if (!("provider" in $$source)) {
            this["provider"] = "";
        }
        if (!("http_code" in $$source)) {
            this["http_code"] = 0;
        }
        if (!("input_tokens" in $$source)) {
            this["input_tokens"] = 0;
        }
        if (!("output_tokens" in $$source)) {
            this["output_tokens"] = 0;
        }
        if (!("cache_create_tokens" in $$source)) {
            this["cache_create_tokens"] = 0;
        }
        if (!("cache_read_tokens" in $$source)) {
            this["cache_read_tokens"] = 0;
        }
        if (!("reasoning_tokens" in $$source)) {
            this["reasoning_tokens"] = 0;
        }
        if (!("is_stream" in $$source)) {
            this["is_stream"] = false;
        }
        if (!("duration_sec" in $$source)) {
            this["duration_sec"] = 0;
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = null;
        }
        if (!("synced_to_server" in $$source)) {
            this["synced_to_server"] = false;
        }
        if (!("input_cost" in $$source)) {
            this["input_cost"] = 0;
        }
        if (!("output_cost" in $$source)) {
            this["output_cost"] = 0;
        }
        if (!("cache_create_cost" in $$source)) {
            this["cache_create_cost"] = 0;
        }
        if (!("cache_read_cost" in $$source)) {
            this["cache_read_cost"] = 0;
        }
        if (!("ephemeral_5m_cost" in $$source)) {
            this["ephemeral_5m_cost"] = 0;
        }
        if (!("ephemeral_1h_cost" in $$source)) {
            this["ephemeral_1h_cost"] = 0;
        }
        if (!("total_cost" in $$source)) {
            this["total_cost"] = 0;
        }
        if (!("has_pricing" in $$source)) {
            this["has_pricing"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RequestLog instance from a string or object.
     */
    static createFrom($$source: any = {}): RequestLog {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RequestLog($$parsedSource as Partial<RequestLog>);
    }
}

// Private type creation functions
const $$createType0 = LogStatsSeries.createFrom;
const $$createType1 = $Create.Array($$createType0);
